plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-67
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "Gemfile"
  - "Gimefile.lock"
  - "bin/"